/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalShop;

/**
 *
 * @author Sabhya
 */
public class userTable extends javax.swing.JFrame {

    /**
     * Creates new form userTable
     */
    public userTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        samplePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("samplePU").createEntityManager();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("DBnetbeans?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        tbluserQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery.getResultList();
        tbluserQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery1.getResultList();
        tbluserQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery2.getResultList();
        tbluserQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery3.getResultList();
        tbluserQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery4.getResultList();
        tbluserQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery5.getResultList();
        tbluserQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Tbluser t");
        tbluserList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tbluserQuery6.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("All User Details");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tbluserList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fpassword}"));
        columnBinding.setColumnName("Fpassword");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fusername}"));
        columnBinding.setColumnName("Fusername");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(293, 293, 293))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.persistence.EntityManager samplePUEntityManager;
    private java.util.List<MedicalShop.Tbluser> tbluserList;
    private java.util.List<MedicalShop.Tbluser> tbluserList1;
    private java.util.List<MedicalShop.Tbluser> tbluserList2;
    private java.util.List<MedicalShop.Tbluser> tbluserList3;
    private java.util.List<MedicalShop.Tbluser> tbluserList4;
    private java.util.List<MedicalShop.Tbluser> tbluserList5;
    private java.util.List<MedicalShop.Tbluser> tbluserList6;
    private javax.persistence.Query tbluserQuery;
    private javax.persistence.Query tbluserQuery1;
    private javax.persistence.Query tbluserQuery2;
    private javax.persistence.Query tbluserQuery3;
    private javax.persistence.Query tbluserQuery4;
    private javax.persistence.Query tbluserQuery5;
    private javax.persistence.Query tbluserQuery6;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
